### ISSUE TITLE
Build Assurance Cases for the Project

### ISSUE THREAD

**Issue by zdfowler** [zdfowler/cybr8420-project#1]
5 claims

Follow grading criteria - see [https://robinagandhi.github.io/swa/slides/lecture-2/assurance-case-exercise.html#5](https://robinagandhi.github.io/swa/slides/lecture-2/assurance-case-exercise.html#5)

Hint: look at the security requirements as a starting place.

We do not have to create the evidence at this point.  We do need to create 5 top-level claims for this issue.

**Comment by lisazilli** [comment]
I misunderstood the assignment, I thought we had to create evidence for all 5 assurance cases. But, I've only done the one diagram at this point, so I'm not too far ahead of the assignment.

I went ahead and added 3 of the 5 assurance cases to a file in the master branch. Feel free to change them and/or add the rest before class.

**Comment by zdfowler** [comment]
I committed an update to the assurance case file.  I'm looking forward to his feedback. Commit ffc0e89515455d5a9daa4759cec09decc72d84a5

**Comment by zdfowler** [comment]
Mostly done, but we still are on the fence about #4.

**Comment by zdfowler** [comment]
Let's review syntax for the document today (claim/rebuttal numbering, Goal Structuring Notation, etc.)

**Comment by zdfowler** [comment]
Updated Lucidchart; ready to go!
